on:
  push:
    tags:
      - 'v*'
  
name: Update pkg.go.dev index
  
jobs:
  bump-index:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Ping endpoint
      run: curl "https://proxy.golang.org/github.com/$OWNER/$REPO/@v/$TAG.info"
      env:
        TAG: ${{ github.ref }}
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.repository }}