on:
  push:
    tags:
      - 'v*'
  
name: Update pkg.go.dev index
  
jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
    - name: Run tests
      run: |
        go test -v ./...
    - name: Ping endpoint
      run: curl "https://proxy.golang.org/github.com/$REPO/@v/$TAG.info"
      env:
        TAG: ${{ github.ref_name }}
        REPO: ${{ github.repository }}
